### ISSUE TITLE
Forsiden bliver ikke vist korrekt

### ISSUE THREAD

**Issue by fharms** [javagruppen/javagruppen.github.io#3]
Forside er i stykker og bliver ikke vist korrekt
![screenshot_20180603-211753](https://user-images.githubusercontent.com/1123285/40890269-c273119e-6773-11e8-90af-828f6382f848.jpg)

**Comment by askarby** [comment]
Jeg har forsøgt at fixe problem (dog kan jeg ikke 100% genskabe det oprindelige look), jeg har brugt `markdownify` til at rendere indholdet, og så introducere et eksplicit "excerpt"-mark (vha. `<!-- more -->` tagget, så man eksplicit kan angive hvor meget af posten man vil ha "bliver vist" på forsiden.

**Comment by askarby** [comment]
Af en aller anden årsag begyndte den blot at vise al indhold uden rendering, som om noget markdown ødelagde abstract-renderingen - da det blev introduceret med hr. Boels introduction (Eksempel) på inkludering af et tweet, gætter jeg på at det kan ha' noget med det at gøre.

Det er dog blevet gjort en del mere robust, nu (omend det oprindelige "look" ikke helt er opnået).

**Comment by mkboel** [comment]
Ja, jeg så det på forsiden, og håbede nogen kunne hjælpe. tweetet så ud til
at virke korrekt når man så på artiklen renderet alene, kun uddraget
forsiden var berørt. Nu ser den god ud på forsiden også

søn. 10. jun. 2018 11.06 skrev Anders Skarby <notifications@github.com>:

**Comment by fharms** [comment]
Ikke er problem mere
